# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20191216_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Category',
            new_name='category_key',
        ),
    ]
